### ISSUE TITLE
[Bug]Error in Cleanroom Loader

### ISSUE THREAD

**Issue by ghost** [dercodeKoenig/AdvancedRocketry#27]
## Version of Advanced Rocketry
2.1.3-1

>Why is this important?
>Knowing the version of Advanced Rocketry helps us narrow down an offending piece of code faster because we can easily determine what code is added and when.]

## Have you verified this is an issue in the latest unstable build
- [x] N

>[Why is this important?
>If you're not testing with the latest build, you may be encountering a bug that's already been fixed.
>Reporting bugs that have already been fixed wastes everyone's time.  (please look in open issues too, somebody else could have already reported it!)]

## Version of LibVulpes
0.4.3

>Why is this important?
>Advanced rocketry depends on a library mod (LibVulpes), some errors can really be in that mod.  So knowing the verison helps us not only start looking for fixes there without you needing to anwer more questions, it also helps us know if you have a version mismatch.]

## Version of Minecraft
1.12.2 with Cleanroom loader 0.2.3

>Why is this important?
>Different versions of minecraft have different codebases for Advanced Rocketry.  Knowing the version of minecraft (and thus AR) helps us pinpoint issues quicker!]

## Does this occur without other mods installed
- [x] Y

>[Why is this important?  
>Sometimes interactions between mods cause issues.  While it can be a problem with Advanced Rocketry, sometimes it's not.  When there are a lot of mods, it can take bugtesters HOURS to go through the list to determine the root cause.  When there are a lot of bug reports, that can add DAYS to the time it takes to fix a large set of issues.]

## Crash report or log or visualVM (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
Error message(not crashing the game)
```
[11:16:15] [main/ERROR] [Foundation]: Error registering transformer class $wrapper.zmaster587.advancedRocketry.asm.ClassTransformer
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$2(TransformerDelegate.java:159) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.registerTransformer(ActualClassLoader.java:160) [foundation-0.13.9.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:123) [CoreModManager$FMLPluginWrapper.class:?]
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:103) [LaunchHandler.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    zmaster587/advancedRocketry/asm/ClassTransformer.transform(Ljava/lang/String;Ljava/lang/String;[B)[B @691: getfield
  Reason:
    Type integer (current frame, stack[0]) is not assignable to 'org/objectweb/asm/tree/MethodNode'
  Current Frame:
    bci: @691
    flags: { }
    locals: { 'zmaster587/advancedRocketry/asm/ClassTransformer', 'java/lang/String', 'java/lang/String', '[B', 'java/lang/String', 'org/objectweb/asm/tree/ClassNode', 'org/objectweb/asm/tree/MethodNode', 'org/objectweb/asm/tree/InsnList', 'org/objectweb/asm/tree/LabelNode', top, 'org/objectweb/asm/tree/AbstractInsnNode', integer, integer, integer }
    stack: { integer }
  Bytecode:
    0000000: 2b10 2e10 2fb6 0125 3a04 1904 2a12 43b7
    0000010: 0129 b601 2d99 012f b801 3313 0135 b601
    0000020: 399c 0123 2a2d b701 3d3a 052a 1905 2a12
    0000030: 7cb7 0129 bb01 3f59 b701 4013 0142 b601
    0000040: 462a 1219 b701 29b6 0146 1301 48b6 0146
    0000050: 2a12 46b7 0129 b601 4613 014a b601 46b6
    0000060: 014d b701 513a 0619 06c6 00c9 bb01 5359
    0000070: b701 543a 0701 3a08 013a 0a06 360b 0636
    0000080: 0c03 360d 1906 b401 5ab6 015e 0464 360e
    0000090: 150e 9b00 3819 06b4 015a 150e b601 673a
    00000a0: 0f19 0fb6 016a 1100 c6a0 001b 840b ff15
    00000b0: 0b9a 0013 190f b601 6e3a 0815 0e04 6036
    00000c0: 0da7 0009 840e ffa7 ffc9 150d 360e 150e
    00000d0: 1906 b401 5ab6 015e a200 3819 06b4 015a
    00000e0: 150e b601 673a 0f19 0fb6 016a 1019 a000
    00000f0: 1c84 0cff 150c 9a00 1419 06b4 015a 150e
    0000100: 0464 b601 673a 0aa7 0009 840e 01a7 ffc1
    0000110: 1908 190a a500 1b19 083a 0919 08b6 016e
    0000120: 3a08 1906 b401 5a19 09b6 0172 a7ff e4a7
    0000130: 000e b201 7813 017a b901 8002 002a 1905
    0000140: b701 84b0 1904 2a12 1fb7 0129 b601 2d99
    0000150: 010c 2a2d b701 3d3a 052a 1905 2a12 6ab7
    0000160: 0129 1301 85b7 0151 3a06 1906 c600 ddbb
    0000170: 0153 59b7 0154 3a07 bb01 8759 b701 883a
    0000180: 0801 3a0a 0436 0b10 0736 0c03 360d 150d
    0000190: 1906 b401 5ab6 015e a200 6919 06b4 015a
    00001a0: 150d b601 673a 0a19 0ab6 016a 1100 b6a0
    00001b0: 004c 150b 840b ff9a 0044 150d 1906 b401
    00001c0: 5ab6 015e a200 3d19 06b4 015a 150d 840d
    00001d0: 01b6 0167 3a09 1909 b601 6a10 19a0 ffdd
    00001e0: 150c 840c ff9a ffd5 1909 b601 8bb6 018b
    00001f0: b601 8bc0 0187 3a08 a700 0984 0d01 a7ff
    0000200: 9019 07bb 018d 5910 1903 b701 90b6 0193
    0000210: 1907 bb01 9559 1100 b813 0197 1301 9913
    0000220: 019a 03b7 019d b601 9319 07bb 019f 5911
    0000230: 0099 1908 b701 a2b6 0193 1906 b401 5a19
    0000240: 0a19 07b6 01a6 a700 0eb2 0178 1301 a8b9
    0000250: 0180 0200 2a19 05b7 0184 b019 042a 1222
    0000260: b701 29b6 012d 9901 0b2a 2db7 013d 3a05
    0000270: 2a19 052a 126a b701 2913 0185 b701 513a
    0000280: 0619 06c6 00dc bb01 5359 b701 543a 07bb
    0000290: 0187 59b7 0188 3a08 013a 0a04 360b 1007
    00002a0: 360c 0336 0d15 0d19 06b4 015a b601 5ea2
    00002b0: 0068 03b4 015a 150d b601 673a 0a19 0ab6
    00002c0: 016a 1100 b7a0 004c 150b 840b ff9a 0044
    00002d0: 150d 1906 b401 5ab6 015e a200 3d19 06b4
    00002e0: 015a 150d 840d 01b6 0167 3a09 1909 b601
    00002f0: 6a10 19a0 ffdd 150c 840c ff9a ffd5 1909
    0000300: b601 8bb6 018b b601 8bc0 0187 3a08 a700
    0000310: 0984 0d01 a7ff 9119 07bb 018d 5910 1903
    0000320: b701 90b6 0193 1907 bb01 9559 1100 b813
    0000330: 0197 1301 9913 019a 03b7 019d b601 9319
    0000340: 07bb 019f 5911 0099 1908 b701 a2b6 0193
    0000350: 1906 b401 5a19 0a19 07b6 01a6 a700 0eb2
    0000360: 0178 1301 aab9 0180 0200 2a19 05b7 0184
    0000370: b019 042a 1219 b701 29b6 012d 9a00 2d19
    0000380: 042a 1228 b701 29b6 012d 9a00 1f19 042a
    0000390: 122b b701 29b6 012d 9a00 1119 042a 122e
    00003a0: b701 29b6 012d 9900 c22a 2db7 013d 3a05
    00003b0: 2a19 052a 126a b701 2913 0185 b701 513a
    00003c0: 0619 06c6 009e bb01 5359 b701 543a 0703
    00003d0: 3609 0336 0b15 0b19 06b4 015a b601 5ea2
    00003e0: 0026 1906 b401 5a15 0bb6 0167 3a0a 190a
    00003f0: b601 6a10 19a0 000a 150b 3609 a700 0984
    0000400: 0b01 a7ff d319 06b4 015a 1509 b601 673a
    0000410: 0819 07bb 018d 5910 1903 b701 90b6 0193
    0000420: 1907 bb01 9559 1100 b813 01ac 1301 aebb
    0000430: 013f 59b7 0140 1301 42b6 0146 2a12 19b7
    0000440: 0129 b601 4613 01b0 b601 46b6 014d 03b7
    0000450: 019d b601 9319 06b4 015a 1908 1907 b601
    0000460: b32a 1905 b701 84b0 1904 2a12 37b7 0129
    0000470: b601 2d99 010f 2a2d b701 3d3a 052a 1905
    0000480: 2a12 76b7 0129 bb01 3f59 b701 4013 0142
    0000490: b601 462a 123d b701 29b6 0146 1301 b5b6
    00004a0: 0146 2a12 40b7 0129 b601 4613 01b7 b601
    00004b0: 46b6 014d b701 513a 0619 06c6 00b5 bb01
    00004c0: 5359 b701 543a 0701 3a08 1906 b401 5ab6
    00004d0: 015e 0464 3609 1509 9b00 2719 06b4 015a
    00004e0: 1509 b601 673a 0a19 0ab6 016a 1100 aca0
    00004f0: 000a 190a 3a08 a700 0984 09ff a7ff da19
    0000500: 07bb 018d 5910 1903 b701 90b6 0193 1907
    0000510: bb01 8d59 1019 04b7 0190 b601 9319 07bb
    0000520: 0195 5911 00b8 1301 b913 01bb bb01 3f59
    0000530: b701 4013 0142 b601 462a 1237 b701 29b6
    0000540: 0146 1301 b5b6 0146 2a12 3db7 0129 b601
    0000550: 4613 01b0 b601 46b6 014d 03b7 019d b601
    0000560: 9319 06b4 015a 1908 1907 b601 b3a7 000e
    0000570: b201 7813 01bd b901 8002 002a 1905 b701
    0000580: 84b0 2db0                              
  Stackmap Table:
    full_frame(@144,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Object[#356],Top,Object[#356],Integer,Integer,Integer,Integer},{})
    same_frame(@196)
    chop_frame(@202,1)
    append_frame(@206,Integer)
    same_frame(@266)
    chop_frame(@272,1)
    full_frame(@303,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342]},{})
    same_frame(@306)
    same_frame(@317)
    chop_frame(@324,2)
    full_frame(@398,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Object[#391],Top,Object[#356],Integer,Integer,Integer},{})
    same_frame(@442)
    same_frame_extended(@507)
    chop_frame(@513,1)
    full_frame(@585,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342]},{})
    same_frame(@596)
    chop_frame(@603,2)
    full_frame(@677,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Object[#391],Top,Object[#356],Integer,Integer,Integer},{})
    same_frame(@720)
    same_frame_extended(@785)
    chop_frame(@791,1)
    full_frame(@863,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342]},{})
    same_frame(@874)
    chop_frame(@881,2)
    same_frame(@937)
    full_frame(@981,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Top,Integer,Top,Integer},{})
    full_frame(@1023,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Top,Integer,Object[#356],Integer},{})
    chop_frame(@1029,2)
    chop_frame(@1121,3)
    chop_frame(@1128,2)
    full_frame(@1238,{Object[#2],Object[#289],Object[#289],Object[#352],Object[#289],Object[#354],Object[#342],Object[#339],Object[#356],Integer},{})
    same_frame(@1273)
    chop_frame(@1279,1)
    chop_frame(@1392,2)
    same_frame(@1403)
    chop_frame(@1410,2)

	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
	at java.lang.Class.newInstance(Class.java:706) ~[?:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:244) ~[ASMTransformerWrapper$TransformerWrapper.class:?]
	at $wrapper.zmaster587.advancedRocketry.asm.ClassTransformer.<init>(Unknown Source) ~[ClassTransformer.class:?]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	... 12 more

```

**Comment by StannisMod** [comment]
Hi there! Please provide the full log through the `pastebin`. 
Your error seems to be an incompatibility with other mods, especially `Foundation`

**Comment by StannisMod** [comment]
Hi there! Cleanroom MC is a full rework of Minecraft 1.12 from Java 8 to Java 21, so it breaks everything that rely on Java 8.
In our mod we have some class transformers that hardly depends on Java version, so it may not work with Cleanroom.
Sad.

**Comment by Krutoy242** [comment]
Since [E2EE](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) players actively using `Java 21+` to play modpack, I would like this issue to be resolved.
